dist: trusty
language: node_js
node_js:
- "stable"
before_script:
- npm install
script:
- npm run build
deploy:
  provider: surge
  project: ./build/
  domain: https://kentico-cloud-sample-app-react-ga-experiments.surge.sh
  skip_cleanup: true
  to: samples/ga-experiments
